### ISSUE TITLE
The game has not started. Join!

### ISSUE THREAD

**Issue by BudgieInWA** [BudgieInWA/nomic-beginnings#1]
### Wait, what is this?

I'm starting a game of Nomic. The creator describes it best:

> Nomic is a game in which changing the rules is a move. In that respect it differs from almost every other game. The primary activity of Nomic is proposing changes in the rules, debating the wisdom of changing them in that way, voting on the changes, deciding what can and cannot be done afterwards, and doing it. Even this core of the game, of course, can be changed.
- [Full rules (as they start)](https://github.com/BudgieInWA/nomic-beginnings/blob/master/RULES.md)
### Join us!

Comment if you want to join. I don't know how often you'll want to make moves or how long the game will go for; we can't know that with the rules constantly changing. In any case, from the rules _"No penalty worse than losing, in the judgment of the player to incur it, may be imposed."_

@Edgeworth suggested making a rule to allow people to join mid-game, so we might do that.

**Comment by Edgeworth** [comment]
I'll give it a shot.

**Comment by hockeyj85** [comment]
:+1:

**Comment by maxhwardg** [comment]
I'm in.

**Comment by BudgieInWA** [comment]
I say we get started. As my username sorts first, I'll start with #2.

**Comment by ArchmageInc** [comment]
@BudgieInWA There is not explicit rule which states that players cannot join in the middle of a game and according to 

> 116 immutable. Whatever is not prohibited or regulated by a rule is permitted and unregulated, with the sole exception of changing the rules (or the contents of the RULES.md in the master branch), which is permitted only when a rule or set of rules explicitly or implicitly permits it.

Which seems to me, a player can join at any time. 

With that said, I wanna play, :)
